### ISSUE TITLE
./configure script missing

### ISSUE THREAD

**Issue by daniestevez** [BatchDrake/cccrack#1]
It seems the `./configure` script is missing from the repo, so I needed to do the following to build:

```
touch NEWS
autoreconf -i
./configure
make
```

In fact the `touch NEWS` is mandatory since otherwise `automake` will fail. I guess the solution is to either include the `./configure` script so that the project can be built by `./configure && make` or to include `NEWS` and write instructions that explain that `autoreconf -i` needs to be used first.

**Comment by BatchDrake** [comment]
Done.
